config/routes.rb
Rails.application.routes.draw do

  # TODO /admin/comments-management
  get '/comments' => 'visitors#comments'

  resources :categories
  resources :episodes
  resources :series

  get '/series/genre/:search' => 'series#genre', :as => :genre

  resources :users
  root to: 'visitors#index'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/signin' => 'sessions#new', :as => :signin
  get '/signout' => 'sessions#destroy', :as => :signout
  get '/auth/failure' => 'sessions#failure'

  get '/load_tile/:id', to: 'series#load_tile', as: 'load_tile'
  get '/load_tile_cover/:id', to: 'series#load_tile_cover', as: 'load_tile_cover'

end

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65280179-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_init_css.html.haml
:css
  .inside-image {
    display: none;
  }
  .carousel .item img {
    width: 150px;
  }

  header, main, footer{
      opacity:0;
  }
  .init-loader { z-index: 100500  }

  .loader {
    opacity: 0.7;
    position: fixed;
    top: calc(50% - 32px);
    left: calc(50% - 32px);
    width: 64px;
    height: 64px;
    border-radius: 50%;
    perspective: 800px;
  }

  .inner {
    position: absolute;
    box-sizing: border-box;
    width: 100%;
    height: 100%;
    border-radius: 50%;
  }

  .inner.one {
    left: 0%;
    top: 0%;
    animation: rotate-one 1s linear infinite;
    border-bottom: 3px solid #1C262B;
  }

  .inner.two {
    right: 0%;
    top: 0%;
    animation: rotate-two 1s linear infinite;
    border-right: 3px solid #1C262B;
  }

  .inner.three {
    right: 0%;
    bottom: 0%;
    animation: rotate-three 1s linear infinite;
    border-top: 3px solid #1C262B;
  }

  @keyframes rotate-one {
    0% {
      transform: rotateX(35deg) rotateY(-45deg) rotateZ(0deg);
    }
    100% {
      transform: rotateX(35deg) rotateY(-45deg) rotateZ(360deg);
    }
  }

  @keyframes rotate-two {
    0% {
      transform: rotateX(50deg) rotateY(10deg) rotateZ(0deg);
    }
    100% {
      transform: rotateX(50deg) rotateY(10deg) rotateZ(360deg);
    }
  }

  @keyframes rotate-three {
    0% {
      transform: rotateX(35deg) rotateY(55deg) rotateZ(0deg);
    }
    100% {
      transform: rotateX(35deg) rotateY(55deg) rotateZ(360deg);
    }
  }

app/views/layouts/_init_js.html.haml
:javascript
	window.tryFirePostponedFunc = function(requiredFlags, func) {
	
	    if (!(Object.prototype.toString.call(window.initializationFlags) === '[object Array]'))
	        return;
	    var i, len = requiredFlags.length;
	    for (i = 0; i < len; i++)
	        if (myInArray(requiredFlags[i], window.initializationFlags) < 0)
	            return;
	    func();
	    return true;
	};
	
	window.addPostponedFunc = function(requiredFlags, func) {
	    if (tryFirePostponedFunc(requiredFlags, func))
	        return;
	    window.funcRequirements = window.funcRequirements || [];
	    window.funcRequirements.push({
	        flags: requiredFlags,
	        func: func
	    });
	};
	
	window.firePostponedFuncs = function() {
	    for (var funcIndex in window.funcRequirements) {
	        if (tryFirePostponedFunc(window.funcRequirements[funcIndex].flags, window.funcRequirements[funcIndex].func))
	            delete window.funcRequirements[funcIndex];
	    }
	}
	
	window.addInitializationFlag = function(flag) {
	    window.initializationFlags = window.initializationFlags || [];
	    window.initializationFlags.push(flag);
	    firePostponedFuncs();
	}
	
	function myInArray( elem, array ) {
		if ( array.indexOf ) {
			return array.indexOf( elem );
		}

		for ( var i = 0, length = array.length; i < length; i++ ) {
			if ( array[ i ] === elem ) {
				return i;
			}
		}

		return -1;
	}

app/views/layouts/_last_comments.html.haml
.panel.panel-info
  .panel-body
    %ul.nav.nav-tabs{:style => "margin-bottom: 15px;"}
      %li.active
        %a{"data-toggle" => "tab", :href => "#vk"} Коментарі Вк

    #myTabContent.tab-content
      #vk.tab-pane.fade.active.in{ "data-turbolinks-eval" => "always" }
        %p
          #vk_comments{"data-turbolinks-eval" => "always"}

:css
  #comments div[id^='___comments_'], #comments div[id^='___comments_'] iframe {
    width: 100% !important;
  }

app/views/layouts/_messages.html.haml
.row
  .col-sm-12
    -# Rails flash messages styled for Bootstrap 3.0
    - flash.each do |name, msg|
      - if msg.is_a?(String)
        %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
          %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
          = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
.navbar.navbar-info
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-responsive-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{href: root_path, style: 'padding-top: 3px;'}
        = image_tag 'logo.png'
    .navbar-collapse.collapse.navbar-responsive-collapse
      %ul.nav.navbar-nav{ "data-hover"=>"dropdown", "data-animations"=>"zoomIn fadeInLeft fadeInUp fadeInRight" }
        %li.dropdown
          %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => category_path(1), class: 'visible-xs visible-sm'}
            %b Аніме
            %b.caret
          %a.dropdown-toggle{"data-target" => "#", "data-toggler" => "dropdown", :href => category_path(1), class: 'hidden-xs hidden-sm'}
            %b Аніме
            %b.caret
          %ul.dropdown-menu
            %li
              = link_to 'Завершені', category_path(4)
            %li
              = link_to 'Онґоінґи', category_path(5)
            %li
              = link_to 'Неонґоіґи', category_path(6)
            // %li.divider
            // %li.dropdown-header Dropdown header
            %li
              = link_to 'ОВА', category_path(7)
            %li
              = link_to 'Аніме фільми', category_path(8)
        %li
          = link_to '<b>Серіали</b>'.html_safe, category_path(2)
        -#%li.dropdown
          %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
            %b Серіали
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "javascript:void(0)"} Завершені
            %li
              %a{:href => "javascript:void(0)"} Онґоінґи
            %li
              %a{:href => "javascript:void(0)"} Неонґоіґи
        %li
          = link_to '<b>Фільми</b>'.html_safe, category_path(3)
        -#%li.dropdown
          %a.dropdown-toggle{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html"}
            %b Фільми
            %b.caret
          %ul.dropdown-menu
            %li
              %a{:href => "javascript:void(0)"} Фантастика
            %li
              %a{:href => "javascript:void(0)"} Містика

      -#%form.navbar-form.navbar-left
      -#= form_tag(series_path, :method => "get", id: "search-form")
      -#  = text_field_tag :search, params[:search], placeholder: "Пошук"
      -#  = submit_tag "Search", :name => nil
      = form_tag series_index_path, :method => "get", class: ' navbar-form navbar-left' do
        = text_field_tag :search, params[:search], placeholder: "Пошук", class: 'form-control col-lg-8'
      = render 'layouts/navigation_links'
  = render 'layouts/site_top'

app/views/layouts/_navigation_links.html.haml
%ul.nav.navbar-nav.navbar-right
  -#%li
    %a{:href => "javascript:void(0)"} Link

  - if user_signed_in?
    %li.dropdown
      %a.dropdown-toggle.profile{"data-target" => "#", "data-toggle" => "dropdown", :href => "bootstrap-elements.html", style: 'padding-top: 5px;padding-bottom: 5px'}
        %img{style: "background-image:url('#{current_user.avatar}');vertical-align: middle;height:50px;width:50px;border-radius: 50%;"}
        %b.caret
      %ul.dropdown-menu
        %li
          - if admin?
            %li
              = link_to new_series_path do
                %i.mdi-content-add-box{style:'vertical-align: middle'}
                Додати новий реліз
          %li
            = link_to '#' do
              %i.mdi-communication-email{style:'vertical-align: middle'}
              = current_user.email
          -#%li
            = link_to users_path do
              %i.mdi-social-group{style:'vertical-align: middle'}
              Користувачі сайту
          %li.divider
          %li
            = link_to signout_path do
              %i.mdi-content-backspace{style:'vertical-align: middle'}
              Вийти

  - else
    %li
      = link_to signin_path do
        %i.mdi-action-input{style:'vertical-align: middle;font-size: 18px'}
        Увійти

app/views/layouts/_site_top.haml
.site-top
  #carousel-example-generic.carousel.slide{"data-ride" => "carousel"}
    %ol.carousel-indicators
      %li.active{"data-slide-to" => "0", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "1", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "2", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "3", "data-target" => "#carousel-example-generic"}
      %li{"data-slide-to" => "4", "data-target" => "#carousel-example-generic"}
    .carousel-inner{:role => "listbox"}
      .item.active
        = image_tag "slider/img1.png"
      .item
        = image_tag "slider/img2.png"
      .item
        = image_tag "slider/img3.png"
      .item
        = image_tag "slider/img4.png"
      .item
        = image_tag "slider/img5.png"
    %a.left.carousel-control{"data-slide" => "prev", :href => "#carousel-example-generic", :role => "button"}
      %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
      %span.sr-only Previous
    %a.right.carousel-control{"data-slide" => "next", :href => "#carousel-example-generic", :role => "button"}
      %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
      %span.sr-only Next

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'UkrDub.net - аніме та серіали українською'
    = favicon_link_tag
    %meta{:name => "description", :content => content_for?(:description) ? yield(:description) : "UkrDub - це вітчизняний фандаб проект, що займається перекладом і озвученням аніме та серіалів українською мовою."}

    %meta{:content => content_for?(:url) ? yield(:url) : 'http://www.ukrdub.net', :property => "og:url"}
    %meta{:content => content_for?(:title) ? yield(:title) : 'UkrDub.net - аніме та серіали українською', :property => "og:title"}
    %meta{:content => content_for?(:description) ? yield(:description) : "UkrDub - це вітчизняний фандаб проект, що займається перекладом і озвученням аніме та серіалів українською мовою.", :property => "og:description"}
    %meta{:content => content_for?(:image) ? yield(:image) : 'http://res.cloudinary.com/ukrdub/image/upload/v1444766589/public/newlogo.png', :property => "og:image"}/
    
    = render 'layouts/init_js'
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application', 'data-turbolinks-track' => true, :async => true
    -#%script{:src => "//vk.com/js/api/openapi.js?116", :type => "text/javascript", :async => true}
    = csrf_meta_tags
  %body
    .init-loader
      .loader
        .inner.one
        .inner.two
        .inner.three
    %header.header-decorator
      = render 'layouts/navigation'
    %main{:role => "main"}
      .container
        = render 'layouts/messages'
        = yield
        .clearfix
    %footer.footer
      %div{style: 'background-color: #385762;height: 125px;width:100%;'}
        .container
          = render 'layouts/footer'
          .center-block.top-me-please{style: 'width:56px;margin-top:-26px;'}
            %a.btn.btn-info.btn-fab.btn-raised.mdi-navigation-expand-less.scroll-to-top{:href => "#"}